dist: bionic
language: go

go:
- 1.13.x

# skip non-trunk PMM-XXXX branch builds, but still build pull requests
branches:
  except:
    - /^PMM\-\d{4}/

env:
- POSTGRESQL_IMAGE=postgres:9.4
- POSTGRESQL_IMAGE=postgres:9.5
- POSTGRESQL_IMAGE=postgres:9.6
- POSTGRESQL_IMAGE=postgres:10
- POSTGRESQL_IMAGE=postgres:11
- POSTGRESQL_IMAGE=postgres:12

services:
- docker

go_import_path: github.com/percona/postgres_exporter

install:
# install reviewdog and golangci-lin
  - curl https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s
  - curl https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s latest

before_script:
  # static analyze
  - bin/golangci-lint run -c=.golangci-required.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-check
  - bin/golangci-lint run -c=.golangci.yml --out-format=line-number | bin/reviewdog -f=golangci-lint -level=error -reporter=github-pr-review
  # use the same uid as in container
  - sudo usermod -u 999 postgres
  - sudo chown postgres:postgres testdata/ssl/*
  - sudo chmod 0600 testdata/ssl/*

  - docker --version
  - docker-compose --version
  - docker-compose up -d

script:
- make
- make test

after_failure:
- docker-compose logs
#- docker exec postgres_exporter_postgresql cat /etc/passwd
#- ls -l testdata/ssl
#- sudo cat /etc/passwd

notifications:
  email: false
