version: '3'
services:
  postgresql:
    image: ${POSTGRESQL_IMAGE:-postgres}
    ports:
      - 127.0.0.1:5432:5432
    environment:
      - POSTGRES_USER=root
  postgressl:
    build:
      dockerfile: Dockerfile_ssl
      context: ./docker
    ports:
        - 5433:5432
    command: -c ssl=on -c ssl_cert_file=/var/lib/postgresql/server.crt -c ssl_key_file=/var/lib/postgresql/server.key
    environment:
      - POSTGRES_USER=root

